apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /ArkOcpIPI_lab/kewel/jenkins
    server: gbnasArkOcpIPI_lab
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
